package ir.siriusapps.moneysave.presenter.ui.appEnum

enum class BankName {
    MELLI, TOSEHSADERAT, SANATOMADAN, MASKAN, POSTBANKIRAN,
    TOEHVATAVON, EGHTESADNOVIN, PARSIYAN, PASARGAD, KARAFARIN, SAMAN,
    SINA, SARMAYEH, TAT, SHAR, DEY, SADERRAT, MELLAT,
    TEJARAT, REFAH, ANSAR, MEHREEGHTESAD,SEPAH,KESHAVARZY,UNDEFINE
}